### ISSUE TITLE
频繁播放、停止，出现空指针异常

### ISSUE THREAD

**Issue by BrightLin** [Mr-wangyong/ImageFrame#10]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.InputStream android.content.res.Resources.openRawResource(int)' on a null object reference
                                                                        at com.mrwang.imageframe.BitmapLoadUtils.decodeSampledBitmapFromRes(BitmapLoadUtils.java:69)

**Comment by BrightLin** [comment]
`E/AndroidRuntime: FATAL EXCEPTION: WorkHandler
                                                                    Process: com.ubtedu.alpha1x, PID: 15836
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.InputStream android.content.res.Resources.openRawResource(int)' on a null object reference
                                                                        at com.mrwang.imageframe.BitmapLoadUtils.decodeSampledBitmapFromRes(BitmapLoadUtils.java:69)
                                                                        at com.mrwang.imageframe.ImageFrameHandler.loadInThreadFromRes(ImageFrameHandler.java:331)
                                                                        at com.mrwang.imageframe.ImageFrameHandler.handleMessage(ImageFrameHandler.java:367)
                                                                        at com.mrwang.imageframe.WorkHandler$1.handleMessage(WorkHandler.java:29)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                        at android.os.Looper.loop(Looper.java:203)
                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by Mr-wangyong** [comment]
能否提供一下具体场景，从 log 上看是给的数组有空元素，难道是双线程问题？

**Comment by hello-ring** [comment]
我也出现了这个问题，是偶然出现的

**Comment by hello-ring** [comment]
> 能否提供一下具体场景，从 log 上看是给的数组有空元素，难道是双线程问题？

就是正常播放的场景
