### ISSUE TITLE
点击按钮播放过快崩溃

### ISSUE THREAD

**Issue by jutao** [Mr-wangyong/ImageFrame#5]
错误信息如下：
 E/AndroidRuntime: FATAL EXCEPTION: WorkHandler
                                                                                         Process: com.example.administrator.liveanimation, PID: 32047
                                                                                         java.util.ConcurrentModificationException
                                                                                             at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:578)
                                                                                             at com.mrwang.imageframe.WorkHandler$1.handleMessage(WorkHandler.java:34)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                             at android.os.Looper.loop(Looper.java:207)
                                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Mr-wangyong** [comment]
嗯 好的 感谢你的反馈 稍后我修复一下

**Comment by Mr-wangyong** [comment]
已修复,感谢您的反馈
