### ISSUE TITLE
快速切换界面，调用stop方法会crash

### ISSUE THREAD

**Issue by king19910525** [Mr-wangyong/ImageFrame#8]
用Monkey测试出现
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at com.gubei.tool.imageframe.WorkHandler$1.handleMessage(WorkHandler.java:28)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:179)
	at android.os.HandlerThread.run(HandlerThread.java:61)

public void removeMessageProxy(WorkMessageProxy proxy) {
    initMessageProxyList();
    messageProxyList.remove(proxy);
  }好像是List移除时出错 不能确定

**Comment by Mr-wangyong** [comment]
这个 移除的方法 不建议在子线程,注意 add和 remove 时候的线程环境,不建议在多线程环境下添加移除监听器
